import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, collection, onSnapshot, query, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const safe=(v='')=>String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[ch]));
try{
 const app=initializeApp(firebaseConfig),db=getFirestore(app);
 const listen=(name,cb)=>onSnapshot(query(collection(db,name),orderBy('createdAt','desc')),snap=>cb(snap.docs.map(d=>({id:d.id,...d.data()}))),err=>console.warn('Firebase public',name,err.message));
 listen('customServices',items=>{const first=document.querySelector('.service-list'); if(!first||!items.length)return; items.forEach(s=>{if(document.querySelector(`[data-fb-service="${s.id}"]`))return; first.insertAdjacentHTML('beforeend',`<article data-fb-service="${safe(s.id)}"><img src="${safe(s.imageUrl||'assets/images/visual-05.svg')}"><div><b>${safe(s.title)}</b><p>${safe(s.description||'خدمة مضافة من لوحة المشرف')}</p><button onclick="openRequest('${safe(s.targetPage||'general')}','${safe(s.title)}')">اطلب هذه الخدمة</button></div></article>`)});});
 listen('experts',items=>{const grid=document.getElementById('expertsGrid'); if(!grid||!items.length)return; items.forEach(e=>{if(document.querySelector(`[data-fb-expert="${e.id}"]`))return; grid.insertAdjacentHTML('afterbegin',`<article class="expert-card" data-fb-expert="${safe(e.id)}"><img src="${safe(e.imageUrl||'assets/images/visual-12.svg')}"><h3>${safe(e.name)}</h3><p>${safe(e.field||'خبير أكاديمي')} - ${safe(e.country||'')}</p><div>⭐ ${safe(e.rating||'4.8')} <span>${safe(e.experience||'خبرة')}</span></div><button onclick="openRequest('experts','استشارة مع ${safe(e.name)}')">طلب الخبير</button></article>`)});});
 listen('journals',items=>{const zone=document.getElementById('journalZone'); if(!zone||!items.length)return; let box=document.getElementById('fbJournals'); if(!box){zone.insertAdjacentHTML('afterbegin','<div class="journal-country" id="fbJournals"><h3>مجلات مضافة من لوحة المشرف</h3><div class="journal-grid"></div></div>');box=document.querySelector('#fbJournals .journal-grid')} items.forEach(j=>{if(document.querySelector(`[data-fb-journal="${j.id}"]`))return; box.insertAdjacentHTML('afterbegin',`<article data-fb-journal="${safe(j.id)}"><div class="journal-logo">${safe((j.country||'M').slice(0,2))}</div><b>${safe(j.title)}</b><span>${safe(j.issn||'ISSN')}</span><small>${safe(j.field||j.country||'مجلة')}</small></article>`)});});
 listen('previousWorks',items=>{const grid=document.getElementById('worksGrid'); if(!grid||!items.length)return; items.forEach((w,i)=>{if(document.querySelector(`[data-fb-work="${w.id}"]`))return; grid.insertAdjacentHTML('afterbegin',`<article class="work-card" data-fb-work="${safe(w.id)}"><div class="work-num">+</div><span>${safe(w.type||'عمل سابق')}</span><h3>${safe(w.title)}</h3><p>${safe(w.field||'عام')}</p>${w.fileUrl?`<a href="${safe(w.fileUrl)}" target="_blank">فتح الملف</a>`:''}</article>`)});});
 listen('library',items=>{const grid=document.getElementById('libraryGrid'); if(!grid||!items.length)return; items.forEach(l=>{if(document.querySelector(`[data-fb-lib="${l.id}"]`))return; grid.insertAdjacentHTML('afterbegin',`<article class="lib-card" data-fb-lib="${safe(l.id)}"><i class="fa-solid fa-file-lines"></i><span>${safe(l.type||'قالب')}</span><h3>${safe(l.title)}</h3><p>${safe(l.description||'قالب مضاف من لوحة المشرف')}</p>${l.fileUrl?`<a href="${safe(l.fileUrl)}" target="_blank">تحميل</a>`:''}</article>`)});});
 listen('certificates',items=>{const grid=document.getElementById('certGrid'); if(!grid||!items.length)return; items.forEach(c=>{if(document.querySelector(`[data-fb-cert="${c.id}"]`))return; grid.insertAdjacentHTML('afterbegin',`<article class="cert-card" data-fb-cert="${safe(c.id)}"><div class="cert-img"><img src="${safe(c.imageUrl||'assets/images/visual-24.svg')}"><b>${safe(c.tag||'شهادة')}</b></div><h3>${safe(c.title)}</h3><p>${safe(c.description||'')}</p>${c.fileUrl?`<a href="${safe(c.fileUrl)}" target="_blank">فتح الملف</a>`:''}</article>`)});});
 listen('notifications',items=>{if(!items.length)return; const last=items[0]; const t=document.getElementById('toast'); if(t){t.textContent=last.title||last.description||'إشعار جديد';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),5000)}});
}catch(e){console.warn('Firebase public disabled',e.message)}
